/* Generated By:JavaCC: Do not edit this line. Sql.java */
package edu.buffalo.cse.sql;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import edu.buffalo.cse.sql.data.Datum;
import edu.buffalo.cse.sql.plan.PlanNode;

public class Sql {

	public static void main(String[] args) {
		System.out.println("You haven't implemented me yet!");
	}

	public static List<Datum[]> execQuery(
      Map<String, Schema.TableFromFile> tables,
      PlanNode q
    )
    {
	  
    }

	public static List<List<Datum[]>> execFile(File program)
			throws SqlException {
		throw new SqlException("execQuery() is unimplemented");
	}
}